[[redirects]]
  from = "/register"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/pay"
  to = "https://www.paypal.biz/tulsarugby"
  status = 302
  force = true

[[redirects]]
  from = "/map"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/results"
  to = "/schedule.html"
  status = 302
  force = true

[[redirects]]
  from = "/results.html"
  to = "/schedule.html"
  status = 302
  force = true

[[redirects]]
  from = "/qr"
  to = "/schedule.html"
  status = 302
  force = true

[[redirects]]
  from = "/schedule"
  to = "/schedule.html"
  status = 302
  force = true
