[[redirects]]
  from = "/register"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/pay"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/map"
  to = "https://maps.app.goo.gl/4LTpxbKaCLoM8hoz9"
  status = 301
  force = true

[[redirects]]
  from = "/qr"
  to = "/results"
  status = 301
  force = true

[[redirects]]
  from = "/schedule"
  to = "/results"
  status = 301
  force = true